### ISSUE TITLE
documentation for basic setup and running the application

### ISSUE THREAD

**Issue by MarcHauptmann** [stheophil/wahlversprechen#1]
It would be nice to have a small documentation about how to setup the working environment and run the application. This makes it hard to start contributing to the project - specifically when not being an play expert ;-)

In my case I had some trouble setting the version of the play framework. Do I have to specify it via a command line option when calling _sbt_? Also, when running the app via _run_ an exception 'DB plugin is not registered' is raised.

**Comment by stheophil** [comment]
You are absolutely right. I'll try to write a basic setup guide tonight! 

For now, try this: clone the repo to some directory "wahlversprechen". Open a terminal and cd to the wahlversprechen directory. Then run "/path/to/play22/play/" from this directory. That's what I do :-)

**Comment by MarcHauptmann** [comment]
Thanks for your reply! I'm looking forward for your guide.

**Comment by stheophil** [comment]
Done. I've updated the README.md. Let me know what you think.

**Comment by MarcHauptmann** [comment]
Thank you very much! After setting up the configuration properly I was able to run the application :-)

Do the tests pass on your machine?

**Comment by stheophil** [comment]
Actually now that you mention it, no. I renamed a few things in the default data from German to English  and forgot to change the tests accordingly. I'm fixing it right now.

**Comment by stheophil** [comment]
Should be fixed.

**Comment by MarcHauptmann** [comment]
Thanks again!

**Comment by stheophil** [comment]
I've started to add a few known issues and possible enhancements to the issues here on github. In case you want to get your hands dirty :-)

**Comment by MarcHauptmann** [comment]
Thank you! I hope to find some time next weekend. I think I will write/optimize some tests at first to get comfortable with the code (and play).

**Comment by stheophil** [comment]
Good idea. I have some ideas how the tests need to improve (https://github.com/stheophil/wahlversprechen/issues/6) but feel free to write new ones. Every test I wrote encountered a bug.
