### ISSUE TITLE
Extend markdown preview

### ISSUE THREAD

**Issue by optikfluffel** [stheophil/wahlversprechen#36]
> The title, blockquote and blockquote source element on the same page still use ajax-update and render the markdown source. They should get "change button" and a preview too. The text area for writing new texts should have the preview as well.

as [mentioned here](https://github.com/optikfluffel/wahlversprechen/commit/e27b7b45517fbf4dc8958e872cde65f37d98ed95#commitcomment-7767386) by @stheophil
- [ ] Title
- [ ] Blockquote
- [ ] Blockquote Source
- [ ] Create New Entry

**Comment by mknecht** [comment]
I'll look into that these days.

**Comment by stheophil** [comment]
Great. That's the most important issue now.  

Von meinem iPhone gesendet

**Comment by stheophil** [comment]
Although you don't need to bother with the preview for title and blockquote. Too unimportant. But a preview for new entries is important for editors.
