### ISSUE TITLE
Group tags in Admin Preferences 

### ISSUE THREAD

**Issue by mknecht** [stheophil/wahlversprechen#39]
Where should that be done? It's clearly a part of the presentation layer, but I'm not sure where that is in Play. Any recommendations?

Regarding design: Grouping usually means that the columns will end up being of differing length, depending on the distribution of the beginning letters. I find that ugly, usually, so I'd insert “header” entries, leave the splitting up to .sliding() and then render the headers nicely (e.g. the letter capitalized and bold?).

This issue is an extract from #25.

**Comment by stheophil** [comment]
`app/views/adminPrefs.scala.html` is the Play template, which is mostly HTML with very little code. 
`app/assets/javascripts/editing.js` will become the module that is loaded by pages in editing mode. That's where the JS code should go.

I thought of grouping the tags by first letter and showing a list of [tabs](http://getbootstrap.com/components/#nav) to switch between the tag groups. I'm not sure how your design would look like exactly.

**Comment by mknecht** [comment]
I proposed to leave the tags as they are, but add a header between each letter. If you think 26 tabs work better: all fine by me. :) (I have only my test data here, so no idea how many tags there are one the real site, so can't know what work best.)

Sure you don't want an adminPrefs.js for the specific stuff? editing.js is pretty … full.

**Comment by stheophil** [comment]
I don't know the distribution of first letters either :-) 

Maybe you can find out :-) 

Your idea sounds good too, but I wanted to avoid this endless list of tags to scroll through. The groups could be collapsible, though, that would work.

**Comment by stheophil** [comment]
adminPrefs.js is good too. Ideally, it would be the requirejs entry point for the admin page, but I didn't get there yet. Put it in adminPrefs.js and that will be loaded always. At least its in the right place then.

**Comment by mknecht** [comment]
Alright. I'll experiment a bit, and attach a screenshot here, when I've got something working that we can discuss.

**Comment by stheophil** [comment]
BTW, feel free to render the tag view client-side only using the JSON API end points. 

The code could be the first component of the client.js library I'd like to build to access the site data from JS, see https://github.com/stheophil/wahlversprechen/issues/38.

**Comment by mknecht** [comment]
Cool. Will do. More this evening, hopefully.

**Comment by mknecht** [comment]
Hey. Something like this seems to work …

![selection_025](https://cloud.githubusercontent.com/assets/77181/4450484/3c75644a-4826-11e4-99fc-eb52ec575bde.png)

While building that, it occurred to me that we basically need a grid. You know, a table which gives you paging, sorting and filtering. I can either finish the above in short time, or look for a grid. I'd prefer the latter, if you don't mind the dependency, as I'd expect it to be cleaner, faster and more extensible.

Look or try:
https://github.com/mknecht/wahlversprechen/tree/issue-39
https://github.com/mknecht/wahlversprechen.git

**Comment by stheophil** [comment]
Looks good for now. Maybe this will do for the moment. There are more important issues :-)

Would you want to implement a view that shows the tags with low edit distance to find spelling mistakes like in your screenshot? That would save a lot of time.

**Comment by stheophil** [comment]
You might want to add your tag loading code to https://github.com/stheophil/wahlversprechen/blob/master/public/javascripts/client.js

**Comment by mknecht** [comment]
Okay, will finish it and make a pull request.

We need to coordinate better: https://github.com/mknecht/wahlversprechen/blob/issue-39/public/javascripts/client.js

:)
Mind, if I integrate the module-publishing code, too?

**Comment by stheophil** [comment]
Good, but no harm done. Please do merge the module publishing code and 
please see how I used the jsroutes object that the backend generates to 
remove hardcoded API URLs.

Am 2014-09-30 11:53, schrieb Murat Knecht:

**Comment by mknecht** [comment]
@stheophil Saw the url routing. In the prefs.js I'll use it for the template url. In the client.js it cannot be used, if you want others to be able to use that module standalone off the WV server.
