### ISSUE TITLE
Speed up creation of test database in WithFilledTestDatabase

### ISSUE THREAD

**Issue by stheophil** [stheophil/wahlversprechen#6]
Currently, `WithFilledTestDatabase` pulls the test data from several Google Spreadsheets because that is the only import mechanism I have. This is very very slow. 

For test data, a simple SQL file that is streamed directly to PostgresSQL should be enough. 

The test data should include both the content of the Google Sheets and the content inserted in `app/Global.scala` 

The `InitialData` object itself should feed the default data to the database. At the moment, it should always add users and authors because there is no other way to add those and it should add test content when configuration setting `app.initialcontent` is set to some file. 

`WithFilledTestDatabase` could then be removed

**Comment by MarcHauptmann** [comment]
I am working on this issue at the moment. Until now I reworked most of the tests so that each test declares its own test data. I made some good experiences using this testing strategy. So `WithFilledTestDatabase` could be removed. I will issue an pull request when ready.

**Comment by stheophil** [comment]
Great, looking forward to it.

**Comment by stheophil** [comment]
Closed with 8bdeba72ce
